name: Development

on:
  push:
    branches-ignore:
      - "master"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check node and yarn version
        run: |
          echo "node: `node -v`"
          echo "yarn: v`yarn -v`"
      - name: Install dependences
        run: yarn install
      - name: Lint project
        run: yarn lint
      - name: Test project
        run: yarn run test
      - name: Build package
        run: yarn run build:all
      - name: Test built package (Chrome)
        run: yarn run web-ext lint --source-dir ./build/chrome
      - name: Test built package (Firefox)
        run: yarn run web-ext lint --source-dir ./build/firefox
