name: lint
on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: nodenv/actions/node-version@main
        id: nodenv
      - name: Use Node.js ${{ steps.nodenv.outputs.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: "${{ steps.nodenv.outputs.node-version }}"
      - name: yarn install, and yarn lint
        run: |
          yarn install --frozen-lockfile
          yarn lint
